# To update rev numbers, run pre-commit autoupdate
# https://pre-commit.com/#pre-commit-autoupdate
repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.7.0
    hooks:
      - id: isort
        args: ["--profile=black", "--filter-files"]
  - repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      - id: black
        args: ["--line-length=88"]
        language_version: python3
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        language_version: python3
        args:
          [
            "--max-line-length=88",
            "--max-complexity=18",
            "--select=E9,F63",
            "--ignore=E203,E266,E501,W503,F403,F401,E402",
          ]
  # - repo: local
  #   hooks:
  #     - id: commitizen-bump
  #       name: Commitizen bump
  #       language: python
  #       stages: [post-commit]
  #       entry: cz bump
