name: Build documentation

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install dev dependencies
        run: | 
          pip install --upgrade pip
          pip install -r devtools/requirements-dev.txt
      
      - name: Install package
        run: |     
          pip install -e .

      - name: Build and deploy docs
        run: |
          mkdocs gh-deploy --force