name: Lint via pre-commit

on:
  pull_request:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: | 
          pip install pre-commit
          pre-commit install
          pre-commit run -a
